server:
  servlet:
    context-path: /transport

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transport
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm

transport:
  a-pageable:
    page: 0
    size: 2000
    sort-by: id
  delay:
   limits:
    1: 0.5
    30: 1.0
    60: 2.0
    120: 5.0
